const express = require('express');

const app = express();

app.use(express.json());

const PORT = 3000;

/*
    GET - BUSCAR INFORMAÇÕES DENTRO DO SERVIDOR
    POST - INSERIR UMA INFORMAÇÃO NO SERVIDOR
    PUT - ALTERAR UMA INFORMAÇÃO NO SERVIDOR
    PATCH - ALTERAR UMA INFORMAÇÃO ESPECÍFICA NO SERVIDOR
    DELETE - DELETAR UMA INFORMAÇÃO NO SERVIDOR
*/

/*
    TIPOS DE PARÂMETROS

    ROUTE PARAMS => IDENTIFICAR UM RECURSO, EDITAR OU DELETAR ESSE RECURSO
    QUERY PARAMS => PAGINAÇÃO / FILTRO
    BODY PARAMS => OBJETOS DE INSERÇÃO / ALTERAÇÃO
*/

app.listen(PORT, () => {
    console.log('Server is up!');
});



